//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClothesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employe()
        {
            this.transaksis = new HashSet<transaksi>();
        }
    
        public int id_employe { get; set; }
        public string email_employe { get; set; }
        public string username_employe { get; set; }
        public string password { get; set; }
        public string akses { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaksi> transaksis { get; set; }
    }
}
