//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClothesMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaksi
    {
        public int id_transaksi { get; set; }
        public int QOH { get; set; }
        public decimal subtotal { get; set; }
        public Nullable<int> id_employe { get; set; }
        public int id_cart { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual employe employe { get; set; }
    }
}
